# Disable wasmtime cache by default in the Docker image, because the rootfs is likely to be read-only

[cache]
enabled = false

# A directory which exists *must* be specified even though the cache is
# disabled, else wasmtime will try to create it, which might fail if the rootfs
# is mounted as read-only
directory = "/tmp"
