version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels:
      - "A-Dependencies"
      - "Z-Deps-Backend"
    schedule:
      interval: "daily"
    groups:
      aws:
        patterns:
          - "aws-*"
      opentelemetry:
        patterns:
          - "opentelemetry"
          - "opentelemetry-*"
          - "tracing-opentelemetry"
      sentry:
        patterns:
          - "sentry"
          - "sentry-*"
      tracing:
        patterns:
          - "tracing-*"
        exclude-patterns:
          - "tracing-opentelemetry"
      icu:
        patterns:
          - "icu"
          - "icu_*"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "A-Dependencies"
      - "Z-Deps-CI"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/frontend/"
    labels:
      - "A-Dependencies"
      - "Z-Deps-Frontend"
    schedule:
      interval: "daily"
    groups:
      storybook:
        patterns:
         - "storybook"
         - "@storybook/*"
      vitest:
        patterns:
         - "vitest"
         - "@vitest/*"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "vite-*"
      react:
        patterns:
          - "react"
          - "react-*"
      jotai:
        patterns:
          - "jotai"
          - "jotai-*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
      urql:
        patterns:
          - "@urql/*"
      graphql-codegen:
        patterns:
          - "@graphql-codegen/*"
      types:
        patterns:
          - "@types/*"

  - package-ecosystem: "npm"
    directory: "/tools/syn2mas/"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore @types/node until we can upgrade to Node 20
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    groups:
      production:
        dependency-type: "production"
      development:
        dependency-type: "development"