[package]
name = "matrix-authentication-service"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
async-std = { version = "1.8.0", features = ["attributes"] }
tide = "0.16.0"
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
figment = { version = "0.10.5", features = ["env", "yaml"] }
url = "2.2.2"
oauth2-types = { path = "../oauth2-types" }
thiserror = "1.0.25"
async-trait = "0.1.50"
tera = "1.10.0"
anyhow = "1.0.41"
csrf = "0.4.0"
data-encoding = "2.3.2"
time = "0.2.27"
tide-tracing = "0.0.11"
mime = "0.3.16"
sqlx = { version = "0.5.5", features = ["runtime-async-std-rustls", "postgres", "migrate"] }
