[package]
name = "mas-cli"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
tokio = { version = "1.14.0", features = ["full"] }
futures = "0.3.18"
anyhow = "1.0.51"
clap = "3.0.0-beta.5"
dotenv = "0.15.0"
schemars = { version = "0.8.8", features = ["url", "chrono"] }
tower = { version = "0.4.11", features = ["full"] }
tower-http = { version = "0.2.0", features = ["full"] }
hyper = { version = "0.14.15", features = ["full"] }
serde_yaml = "0.8.21"
warp = "0.3.2"
url = "2.2.2"
argon2 = { version = "0.3.1", features = ["password-hash"] }
reqwest = { version = "0.11.7", features = ["rustls-tls"], default-features = false, optional = true }

tracing = "0.1.29"
tracing-subscriber = { version = "0.3.3", features = ["env-filter"] }
tracing-opentelemetry = "0.16.0"
opentelemetry = { version = "0.16.0", features = ["trace", "metrics", "rt-tokio"] }
opentelemetry-http = "0.5.0"
opentelemetry-semantic-conventions = "0.8.0"
opentelemetry-jaeger = { version = "0.15.0", features = ["rt-tokio", "reqwest_collector_client"], optional = true }
opentelemetry-otlp = { version = "0.9.0", features = ["trace", "metrics"], optional = true }
opentelemetry-zipkin = { version = "0.14.0", features = ["reqwest-client", "reqwest-rustls"], default-features = false, optional = true }

mas-config = { path = "../config" }
mas-core = { path = "../core" }
mas-templates = { path = "../templates" }

[dev-dependencies]
indoc = "1.0.3"

[features]
default = ["otlp", "jaeger", "zipkin"]
# Enable OpenTelemetry OTLP exporter. Requires "protoc"
otlp = ["opentelemetry-otlp"]
# Enable OpenTelemetry Jaeger exporter and propagator.
jaeger = ["opentelemetry-jaeger", "reqwest"]
# Enable OpenTelemetry Zipkin exporter and B3 propagator.
zipkin = ["opentelemetry-zipkin", "reqwest"]
