[package]
name = "mas-config"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
tokio = { version = "1.15.0", features = [] }
tracing = { version = "0.1.29", features = ["log"] }
async-trait = "0.1.52"

thiserror = "1.0.30"
anyhow = "1.0.52"

schemars = { version = "0.8.8", features = ["url", "chrono"] }
figment = { version = "0.10.6", features = ["env", "yaml", "test"] }
chrono = { version = "0.4.19", features = ["serde"] }
url = { version = "2.2.2", features = ["serde"] }

serde = { version = "1.0.133", features = ["derive"] }
serde_with = { version = "1.11.0", features = ["hex", "chrono"] }
serde_json = "1.0.74"
sqlx = { version = "0.5.10", features = ["runtime-tokio-rustls", "postgres"] }

rand = "0.8.4"
rsa = { git = "https://github.com/sandhose/rsa.git", branch = "bump-pkcs" }
p256 = { version = "0.10.0", features = ["ecdsa", "pem", "pkcs8"] }
pkcs8 = { version = "0.8.0", features = ["pem"] }
elliptic-curve = { version = "0.11.6", features = ["pem", "pkcs8"] }

indoc = "1.0.3"

mas-jose = { path = "../jose" }
