[package]
name = "mas-config"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
tokio = { version = "1.12.0", features = [] }
tracing = { version = "0.1.29", features = ["log"] }
async-trait = "0.1.51"

thiserror = "1.0.30"
anyhow = "1.0.44"

schemars = { version = "0.8.6", features = ["url", "chrono"] }
figment = { version = "0.10.6", features = ["env", "yaml", "test"] }
chrono = { version = "0.4.19", features = ["serde"] }
url = { version = "2.2.2", features = ["serde"] }

serde = { version = "1.0.130", features = ["derive"] }
serde_with = { version = "1.11.0", features = ["hex", "chrono"] }
serde_json = "1.0.68"
sqlx = { version = "0.5.9", features = ["runtime-tokio-rustls", "postgres"] }

rand = "0.8.4"
rsa = "0.5.0"
k256 = "0.9.6"
pkcs8 = { version = "0.7.6", features = ["pem"] }
elliptic-curve = { version = "0.10.6", features = ["pem"] }
jwt-compact = { version = "0.5.0-beta.1", features = ["with_rsa", "k256"] }

indoc = "1.0.3"
