name: Build the Open Policy Agent policies
description: Installs OPA and builds the policies

runs:
  using: composite
  steps:
    - name: Install Open Policy Agent
      uses: open-policy-agent/setup-opa@v2.2.0
      with:
        version: 0.70.0

    - name: Build the policies
      run: make
      working-directory: ./policies
      shell: sh
