[package]
name = "mas-handlers"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[features]
dev = ["mas-static-files/dev", "mas-templates/dev"]

[dependencies]
# Async runtime
tokio = { version = "1.14.0", features = ["macros"] }

# Logging and tracing
tracing = "0.1.29"

# Error management
thiserror = "1.0.30"
anyhow = "1.0.51"

# Web server
warp = "0.3.2"
hyper = { version = "0.14.16", features = ["full"] }

# Database access
sqlx = { version = "0.5.9", features = ["runtime-tokio-rustls", "postgres"] }

# Various structure (de)serialization
serde = { version = "1.0.131", features = ["derive"] }
serde_with = { version = "1.11.0", features = ["hex", "chrono"] }
serde_json = "1.0.72"
serde_urlencoded = "0.7.0"

# Password hashing
argon2 = { version = "0.3.2", features = ["password-hash"] }

# Crypto, hashing and signing stuff
rsa = { git = "https://github.com/sandhose/rsa.git", branch = "bump-pkcs" }
pkcs8 = { version = "0.8.0", features = ["pem"] }
elliptic-curve = { version = "0.11.6", features = ["pem"] }
chacha20poly1305 = { version = "0.9.0", features = ["std"] }
sha2 = "0.9.8"
crc = "2.1.0"

# Various data types and utilities
data-encoding = "2.3.2"
chrono = { version = "0.4.19", features = ["serde"] }
url = { version = "2.2.2", features = ["serde"] }
mime = "0.3.16"
rand = "0.8.4"
headers = "0.3.5"

oauth2-types = { path = "../oauth2-types" }
mas-config = { path = "../config" }
mas-data-model = { path = "../data-model" }
mas-templates = { path = "../templates" }
mas-static-files = { path = "../static-files" }
mas-storage = { path = "../storage" }
mas-warp-utils = { path = "../warp-utils" }
mas-jose = { path = "../jose" }

[dev-dependencies]
indoc = "1.0.3"
