[package]
name = "mas-templates"
version = "0.1.0"
authors = ["Quentin Gliech <quenting@element.io>"]
edition = "2021"
license = "Apache-2.0"

[features]
dev = []

[dependencies]
tracing = "0.1.29"
tokio = "1.14.0"

anyhow = "1.0.51"
thiserror = "1.0.30"

tera = "1.15.0"
serde = { version = "1.0.131", features = ["derive"] }
serde_json = "1.0.72"

url = "2.2.2"
warp = "0.3.2"

oauth2-types = { path = "../oauth2-types" }
mas-data-model = { path = "../data-model" }
mas-config = { path = "../config" }
